version: "3.9"
volumes:
  letsencrypt-certificates: { }

services:
  web:
    image: unleashorg/unleash-server:latest
        restart: unless-stopped
    networks:
    ports:
      - "4242:4242"

    environment:
      DATABASE_URL: "postgres://${db_user}:${db_password}@${db_ip}:${db_port}/${db_name}"
      EMAIL_PASSWORD: "${scw_token}"
      EMAIL_SENDER: "unleash@sopht.io"
      LOG_LEVEL: "info"
      UNLEASH_URL: "https://unleash.sopht.io"
      EMAIL_HOST: "smtp.tem.scw.cloud"
      EMAIL_PORT: "2465"
      EMAIL_SECURE: "true"
      EMAIL_USER: "40aeb907-0d90-4736-902e-decf73b4c417"

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.odoo.rule=Host(`${dns}`)"
      - "traefik.http.routers.odoo.entrypoints=websecure"
      - "traefik.http.routers.odoo.tls.certresolver=letsencrypt"
      - "traefik.http.routers.odoo.middlewares=compresstraefik"
      - "traefik.http.middlewares.compresstraefik.compress=true"
      - "traefik.http.services.odooservice.loadbalancer.server.port=4242"
  traefik:
    image: traefik:v2.9
    container_name: traefik
    restart: unless-stopped

    command:
      - "--providers.docker=true"
      - "--providers.docker.endpoint=unix:///var/run/docker.sock"
      - "--providers.docker.exposedByDefault=false"
      - "--entryPoints.web.address=:80"
      - "--entryPoints.web.forwardedHeaders.insecure"
      - "--entryPoints.web.proxyProtocol.insecure"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entryPoints.websecure.address=:443"
      - "--entryPoints.websecure.forwardedHeaders.insecure"
      - "--entryPoints.websecure.proxyProtocol.insecure"
      - "--certificatesresolvers.letsencrypt.acme.tlschallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.email=mahdi@outlook.fr"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "letsencrypt-certificates:/letsencrypt"
